// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type HealthCheckResponse struct {
	Status  string `json:"status"`
	Uptime  int64  `json:"uptime"`
	Version string `json:"version"`
}
